### PR TITLE
uses fetch (if available) instead of XMLHttpRequest, to allow use in Service Worker

### PR DESCRIPTION
**Pull request by DougReeder**
Each test suite is now run twice - once with XHR, once with fetch.  Diff ignoring whitespace changes (-b option) to see that the tests themselves are unchanged.

### CODE REVIEW

**Comment by DougReeder** [comment]
codeclimate is flagging the old code, as well as the new, so chopping up the functions into shorter functions is best left for another PR.

travis-ci is using Node v0.10, which has been unsupported for two years. Node v6.0 is the oldest supported version of Node, but allow me to suggest changing to Node v8.0, as that's what I used for testing.

**Comment by silverbucket** [comment]
@DougReeder thanks for the PR, this has also motivated me to clean up the code

**Comment by galfert** [comment]
Nice.

@silverbucket did you create a new release with this yet? Would be great so we can include it in the new rs.js release.

**Comment by silverbucket** [comment]
@galfert just published 2.7.0 which just has @DougReeder's changes

**Pull request merged**
