### PR TITLE
add lookupLink function

### PR DESCRIPTION
**Pull request by michielbdejong**
Would make https://github.com/michielbdejong/ludbud/pull/8 a lot nicer

### CODE REVIEW

**Comment by silverbucket** [comment]
Looks good. Thanks! But why `lookupLink` and `lookupLinks`?

lookupLink can just check whether it's a valid link name itself, then parse the right part of the idx to send back. Or am I missing something?

**Comment by silverbucket** [comment]
(side note: whats your remotestorage address? michielbdejong@michielbdejong.com doesn't have one)

**Comment by michielbdejong** [comment]
Right, I guess there's not many times someone will want to look up  multiple links with the same rel. Removed the intermediate `lookupLinks` function now. I use michiel@5apps.com as my remoteStorage account, and michiel2@5apps.com for testing. I don't have a webfinger record on my own domain now. It's running Known, and I haven't added webfinger to it (yet).

**Comment by silverbucket** [comment]
Ok, will merge and release in a few days (travelling). Thanks a bunch man!

**Comment by silverbucket** [comment]
Oops! forgot about this, merged and will bump the version now.

**Pull request merged**
